version: '3'
services:
  web:
    build:
      context: .
      args:
        - BEATREALTIME_GA_CLIENT_ID=${BEATREALTIME_GA_CLIENT_ID}
        - BEATREALTIME_GA_API_KEY=${BEATREALTIME_GA_API_KEY}
        - BEATREALTIME_TRACKING_ID=${BEATREALTIME_TRACKING_ID}
    ports:
      - "1818:80"

