version: '3'
services:
  web:
    build:
      context: .
      args:
        - BEATREALTIME_GA_CLIENT_ID=${BEATREALTIME_GA_CLIENT_ID}
        - BEATREALTIME_GA_API_KEY=${BEATREALTIME_GA_API_KEY}
        - BEATREALTIME_TRACKING_ID=${BEATREALTIME_TRACKING_ID}
        - BEATREALTIME_SSL_CERT_PATH=${BEATREALTIME_SSL_CERT_PATH}
        - BEATREALTIME_SSL_KEY_PATH=${BEATREALTIME_SSL_KEY_PATH}
    ports:
      - "1817:80"
      - "1818:443"

